version: "3.9"

services:
  minio:
    image: minio/minio:latest
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/login"]
      interval: 10s
      retries: 5
    command: server /data --console-address ":9001"
    ports:
      - "9080:9000"
      - "9081:9001"
    volumes:
      - ./minio_data:/data

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - minio
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_cache:/var/cache/nginx
  
  minio-init-mc:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: [""]
    command: |
      mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
    volumes:
      - ./mc_data:/root/.mc

  minio-init-bucket:
    image: minio/mc
    depends_on:
      - minio-init-mc
    command: |
      mb local/website
    volumes:
      - ./mc_data:/root/.mc

  minio-init-upload:
    image: minio/mc
    depends_on:
      - minio-init-bucket
    command: |
      put /tmp/index.html local/website
    volumes:
      - ./mc_data:/root/.mc
      - ./index.html:/tmp/index.html

  minio-init-access:
    image: minio/mc
    depends_on:
      - minio-init-bucket
    command: |
      anonymous set public local/website
    volumes:
      - ./mc_data:/root/.mc
    